[package]
name = "text-editor"
version = "0.1.0"
edition = "2021"
target = {  }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
crossterm = "0.28.0"
log = "0.4.21"
pad = "0.1.6"
